@startuml
ProviderManager "1" o-right-- "n" AuthenticationProvider
AuthenticationProvider --> Authentication
UsernamePasswordAuthenticationToken --|> 略2
略2 ..|> Authentication
AuthenticationProvider <|.. 略1
略1 <|-- DaoAuthenticationProvider
DaoAuthenticationProvider --> UserDetailsService
DaoAuthenticationProvider --> UsernamePasswordAuthenticationToken
@enduml