@startuml
left to right direction

rectangle "统计评审情况" {
    actor aa as "管理员"
    usecase stPapers as "统计论文得分情况"
    usecase stTasks as "统计教师评审任务完成情况"
    usecase stTips as "统计问题标签引用情况"
    aa --> stPapers
    aa --> stTasks
    aa --> stTips
}

@enduml
