@startuml
left to right direction

frame Encoded {
    frame Header {
        card "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9."
    }
    frame Payload {
        card "eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ."
    }

    frame vs as "verify signaturek" {
        card SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    }
}
frame Decoded {
    frame hd  as "HEADER" {
        cloud c1 [
        {
            "alg": "HS256",
            "typ": "JWT"
        }
        ]
    }
    frame PAYLOAD {
        cloud c2 [
        {
            "sub": "1234567890",
            "name": "John Doe",
            "iat": 1516239022
        }
        ]
    }

    frame VS as "VERIFY SIGNATUREK" {
        cloud c3 [
        HMACSHA256(
        base64UrlEncode(header) + "." +
        base64UrlEncode(payload),
        your-256-bit-secret
        )
        ]
    }
}

hd --> Header
PAYLOAD --> Payload
VS --> vs

@enduml