@startuml
frame 前端{
    node Element
    node Vue
    node axios
    node vuex
    node vuerouter
}
frame 后端 {
    frame SpringBoot {
        node Tomcat
        node ss as "Spring Security"
        node jpa as "Spring Data JPA"
    }
}
前端 -down--> 后端 : JSON对象
后端 -up--> 前端:  JOSN对象

frame 持久化{
    frame ORM工具 {
        node Hibernate
    }
    frame 数据库 {
        node MySQL
    }
    ORM工具 --> 数据库
    数据库 --> ORM工具
}

后端 -down--> 持久化
持久化 -up--> 后端
@enduml