@startuml
actor user as "用户"
participant f as "前端"
participant c as "Contorller"
participant s as "Service"
participant e as "Entity"
participant r as "CommentRepsotory"
user --> f: 选择文件并填入评论
f --> c: request
c --> s: comment
s --> e: new
e --> s: 文件实体对象 file
s --> s: 为file填入父一级评论，评论内容
s --> r: save
r --> s: 保存后的评论实体
s --> c: 评论id
c --> f: response
f --> user: 成功消息
@enduml