@startuml
actor user as "用户"
participant f as "前端"
participant c as "Contorller"
participant s as "Service"
participant e as "TeacherEntity"
participant r as "TeacherRepsotory"
user --> f: 点击教师任务统计页面
f --> s: getInfo
s --> r: findAll
r --> s: teacherEntities
s --> s: 统计数据
s --> c: info
c --> f: response
@enduml
