@startwbs
+ 论文评审评分系统
++ 登陆
+++ 身份验证
++++ 学生
+++++ 论文上传
+++++ 论文下载
+++++ 成绩查看
+++++ 回复评论
+++++ 论文更新
+++- 导师
+++++ 查看所管理的学生论文信息
+++++ 论文下载
+++++ 论文评论
+++++ 论文加问题标签
+++++ 论文评分
++++ 管理员
++++ 系统管理
+++++ 用户管理
+++++ 论文上传通道管理
++++ 论文管理
+++++ 评审情况统计
+++++ 教师评审情况
@endwbs