@startuml
left to right direction

rectangle "论文上传" {
    actor aa as "管理员"
    actor sa as "学生"
    usecase login as "登陆系统"
    usecase setBegin as "开通论文上传通道"
    usecase setEnd as "关闭论文上传通道"
    usecase upload as "上传论文"
    aa --> login
    aa --> setBegin
    aa --> setEnd
    sa --> login
    sa --> upload
}

@enduml