@startuml
left to right direction

actor adimin as aa
actor student as sa
actor teacher as ta
rectangle 论文评审评分系统 {
    usecase login as "用户登陆"
    usecase upload as "上传论文"
    usecase renewPaper as "更新论文"
    usecase mngPaper as "修改论文信息"
    usecase download as "下载论文"
    usecase score as "论文打分"
    usecase review as "论文评审"
    usecase cmt as "论文评论"
    usecase cmtTip as "论文添加问题标签"
    usecase statistic as "评审情况统计"
    usecase sttcPaper as "论文得分情况"
    usecase sttcTeacher as "导师评审任务完成情况"
    usecase mngUer as "学生/教师管理"
}
aa --> login
sa --> login
ta --> login

@enduml