@startuml

(*) -right-> "录入信息（管理员)"
-right-> "导师分配（管理员）"
-right-> "上传论文（学生）"
-right-> "论文评审（导师）"
If "内容无错误" then
--> [true] "论文评分（导师）"
--> "查阅得分（学生）"
else
--> [false] "修改论文（学生）"
--> "更新论文（学生）"
--> "论文评审（导师）"
endif
"查阅得分（学生）" --> "查看评审情况（管理员）"
--> (*)

@enduml