@startuml
actor user as "用户"
participant f as "前端"
participant c as "Contorller"
participant s as "Service"
participant e as "FileEntity"
participant r as "FileRepsotory"
user --> f: 选择文件，填入分数，确定
f --> c: request
c --> s: scoreFile
s --> r: findById
r --> e: new
e --> r: fileEntity
r --> s: fileEntity
s --> s: 为fileEntity填入分数
s --> r: save
r --> e: new
e --> r: fileEntity
r --> s: fileEntity
s --> c 
c --> f: response
@enduml