@startuml
actor user as "用户"
participant f as "前端"
participant c as "Contorller"
participant s as "Service"
participant e as "FileEntity"
participant r as "FileRepsotory"
user --> f: 点击分数统计页面
f --> c: request
c --> s: getInfo
s --> r: findAll
r --> e: new
e --> r: fileEntitys
r --> s: fileEntitys
s --> s: 过滤分类
s --> c: 分类后的fileEntitys
s --> f: response
@enduml