@startuml
database dataBase
node Hibernate
node TopLink
node openjpa
node oOrms as "other ORM frame"
dataBase -up-> oOrms
dataBase -up-> TopLink
dataBase -up-> openjpa
dataBase -up-> Hibernate
rectangle SJpa as "Spring Data Jpa"
cloud Jpa as "Jpa Specification"
SJpa -up-> Jpa
rectangle applicaion
oOrms -up-> SJpa
TopLink -up-> SJpa
openjpa -up-> SJpa
Hibernate -up-> SJpa
Jpa -up-> applicaion
@enduml