@startuml
前端 ->JwtAutenticationController : request
note top: 第一次登陆返回token给前端保存 '/authenticate'
alt 是学生
    JwtAutenticationController -> StudentUserDetailService: loadByUsername
    StudentUserDetailService-> JwtAutenticationController: User(name, password, AuthorityList))
else 是老师
    JwtAutenticationController -> teacherUserDetailService: loadByUsername
    teacherUserDetailService -> JwtAutenticationController: User(name, password, AuthorityList))
end
JwtAutenticationController -> JwtAutenticationController : authenticate
JwtAutenticationController -> JwtTokenUtil : generateToken(userDetails[User])
alt 是学生
    JwtAutenticationController -> AuthenticationManager: authenticate(StudentUsernamePasswordAutenticationToken)
    AuthenticationManager -> StudentDaoAutenticationProvider: authenticate
    StudentDaoAutenticationProvider -> StudentUserDetailService: loadByUsername
    StudentUserDetailService -> StudentDaoAutenticationProvider : UserDtail[User]
    StudentDaoAutenticationProvider -> StudentDaoAutenticationProvider : 一波验证(错误会抛出异常)
else 是老师
    JwtAutenticationController -> AuthenticationManager: authenticate(TeacherUsernamePasswordAutenticationToken)
    AuthenticationManager -> TeacherDaoAutenticationProvider: authenticate
    TeacherDaoAutenticationProvider -> TeacherUserDetailService: loadByUsername
    TeacherUserDetailService -> TeacherDaoAutenticationProvider : UserDtail[User]
    TeacherDaoAutenticationProvider -> TeacherDaoAutenticationProvider : 一波验证(错误会抛出异常)
end
JwtTokenUtil -> JwtAutenticationController : jwtToken
JwtAutenticationController -> 前端: JWTresponse(jwtToken)
@enduml